name = "xlsx"
version = "0.1.0"
defaultTargets = ["Xlsx", "xlsxgen"]

[[lean_lib]]
name = "Xlsx"

[[lean_exe]]
name = "xlsxgen"
root = "Main"

[[lean_lib]]
name = "Lab"

[[require]]
name = "lean-zip"
git = "https://github.com/kim-em/lean-zip"
rev = "2f7a63f38195bc667a926881b55d10c9f8a88eeb"
